sonar.projectKey=Diego_Figueroa_t1
sonar.projectName=Diego Figueroa T1
sonar.host.url=https://sonarqube.ingsoftware.lat/
sonar.scm.disabled=true
sonar.sources=ms-restaurant/src,ms-rewards/src
sonar.tests=ms-restaurant/src,ms-rewards/src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/dist/**,**/node_modules/**
sonar.javascript.lcov.reportPaths=ms-restaurant/coverage/lcov.info,ms-rewards/coverage/lcov.info
sonar.coverage.exclusions=**/*.entity.ts,**/*.dto.ts,**/main.ts,**/app.module.ts
sonar.cpd.exclusions=**/*.entity.ts,**/rabbitmq-outbox.publisher.ts,**/infrastructure/config/environment.ts
